name: exec-test
on: [pull_request]
jobs:
  example-job:
    name: Execute test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Excute test for all
        run: |
          ./gradlew allTests
